### PR TITLE
New Functions: Recursive & Iterative Fibonacci

### PR DESCRIPTION
**Pull request by lussierc**
This pull request is for adding a new function that calculates Fibonacci values, recursively.

### CODE REVIEW

**Comment by Lancasterwu** [comment]
```
def compute_iterative_fibonacci(value):
    if (value == 0):
        return value
    elif (value <= 2):
        return 1
    else:
        x = 0
        y = 1
        for i in range(1, value):
            z = (x + y)
            x = y
            y = z
        return y
```
Can be added to the ibonacci function file

**Comment by lussierc** [comment]
@Lancasterwu Thanks, I will add this soon!

**Comment by lussierc** [comment]
Update: I am currently working to fix the Travis errors, mostly resulting from pylint.

**Comment by Lancasterwu** [comment]
I think you probably need to write the two test cases as one. It seems so much easier.

**Comment by lussierc** [comment]
@Lancasterwu I think you might be right, I will likely try this out very soon!

**Comment by lussierc** [comment]
@Lancasterwu Thank you, I took your advice and my Travis builds now pass.

**Comment by Lancasterwu** [comment]
> @Lancasterwu Thank you, I took your advice and my Travis builds now pass.

You are very welcome!

**Comment by gkapfham** [comment]
Hello @lussierc, I think that you have added code that is breaking the build. Can you look at this very soon and try to resolve the matter? I'd like to merge this PR soon so that this repository has a nice collection of functions that we can use as we are further evaluation the main tool. Thanks for your prompt investigation of this build-breaking commit!

**Comment by lussierc** [comment]
Hi @gkapfham, I will look into fixing this issue later today!

**Comment by lussierc** [comment]
Hi @gkapfham, the build was passing before I added a comment to the code last week. Here is what I am seeing from Travis:

```
tests/test_copies_of.py ./home/travis/.travis/functions: line 104:  4992 Killed                 
pipenv run pytest --cov-config pytest.cov --cov
The command "pipenv run pytest --cov-config pytest.cov --cov" exited with 137.
```

I don't know that it is something that is necessarily wrong with the added code considering the same code passed Travis a few months ago (I removed the comment so it was the same code that passed and it still failed). I was wondering if you had any advice on how to fix this issue.

**Comment by lussierc** [comment]
I have removed the broken commits @gkapfham, everything now passes!

**Pull request merged**
